#! /usr/bin/python3
"""
    Issue: when loading an existing document, the application drops an
    exception.

    The computation of the version on table reload causes a problem.

    Odd hapenstance: a _dcdump in mistnavi:computeMinor.. raises an exception in
    the middle too.. something is off there with the datacore data.

    We should start with extracting the parameters that are passed to datacore
    to see where it breaks down.

    We did not set dc.sp and dc.spid on load. As we use these shortcuts to
    compute the version details we trived to retrive data from an unset path
    with resulted in the bug.

    Saving the sp in s and loading it on startup fixes the issue. This is not
    backwards portable (i.e. old files can't be opened any more).

    Update:
        The real issue was that we computed versions in the project list with
        selected project, which is wrong. Changed the code to use the proper
        pids. This way it remains backwards compatible and actually does what
        it's supposed to do.
"""



